### ISSUE TITLE
Fix: 마이프로필 조회 응답 수정

### ISSUE THREAD

**Issue by yeonjookang** [swyp3-babpool/babpool-backend#110]
## 📌 목적 / 이슈 내용

> 마이프로필 조회 응답 수정

## 📝 상세 내용

- 데이터 중 밥약 히스토리를 현재 DONE으로만 필터링 후 응답
- REVIEW_NOT_REQUIRED 필터링 추가 필요

## ✔ 체크 리스트
- [ ] 쿼리문 수정
- [ ] API TEST

## 💡 비고

- (참고 사항 및 레퍼런스)
- 내용

**Comment by proHyundo** [comment]
기획수정되었습니다! 아래는 수정된 화면정의서 입니다. 코드 변경없이 그대로 진행하면 됩니다 :)
![image](https://github.com/swyp3-babpool/babpool-backend/assets/128882585/45340fc8-732e-4d33-bf6d-99133ae929c5)
