### ISSUE TITLE
refactor(mapper): Mapper 메서드 명 수정

### ISSUE THREAD

**Issue by proHyundo** [swyp3-babpool/babpool-backend#50]
## 📌 목적 / 이슈 내용

> ProfileMapper 및 UserMapper에 존재하는 메서드 명이 적합하지 않습니다.

## 📝 상세 내용

`ProfileMapper.xml`
- ProfileMapper.xml 의 getProfileDetail 을 비즈니스 로직에 가까운 이름이 아닌 DAO 계층에서 사용하기 적합한 findProfileDetailByProfileId 으로 변경 요청드립니다.
   - 또한 resultType에 dao와 dto가 같이 합쳐진 이름이 어색해보입니다. `ProfileDetailDaoDto` 보다 `ProfileDetailResult`, `ProfileDetailResponse` 으로 dto 명을 짓는 것이 적합해 보입니다. 접미사 Dto 는 선택하시면 될 것 같습니다.

`UserMapper.xml`
- UserMapper.xml 의 findMyProfile 또한 ID와 resultType의 변경이 필요해보이나, 그보다 getProfileDetail 의 쿼리와 다른점이 거의 없어 보이는데 중복해서 만드신건지 궁금합니다.

## ✔ 체크 리스트
- [x] @yeonjookang 피드백

## 💡 비고

- (참고 사항 및 레퍼런스)
- [[Spring] DAO, DTO, VO의 개념과 차이점](https://kbwplace.tistory.com/162)

**Comment by yeonjookang** [comment]
메서드명들은 고치도록 하겠습니다! findMyProfile은 userId를 기준으로 데이터를 조회하고 getProfileDetail은 profileId를 기준으로 데이터를 조회합니다! 만약 두 메서드를 하나로 통합한다면 userId 또는 profileId를 조회하기 위한 쿼리를 한번 더 날리면 될 것 같아요! 어떤 방법이 더 낫다고 생각하시나요?

**Comment by proHyundo** [comment]
> 메서드명들은 고치도록 하겠습니다! findMyProfile은 userId를 기준으로 데이터를 조회하고 getProfileDetail은 profileId를 기준으로 데이터를 조회합니다! 만약 두 메서드를 하나로 통합한다면 userId 또는 profileId를 조회하기 위한 쿼리를 한번 더 날리면 될 것 같아요! 어떤 방법이 더 낫다고 생각하시나요?

제가 이해하기로는, UserMapper의 `findMyProfile` 은 나 자신의 프로필 상세정보 조회이고, ProfileMapper의 `getProfileDetail` 은 나 자신을 포함해 특정 프로필 식별값으로 프로필 상세정보 조회인거죠?

1. 만약 하나로 통합한다면 &rarr; 동일한 쿼리 메소드를 사용한다면
프로필 식별 값으로 조회해야 하니, `UserServiceImpl` 의 `getMyPage` 메서드 내에서, userId 으로 profileId 를 먼저 찾는 과정이 필요해질 것 같아요.

2. 만약 지금처럼 분리한다면
이것도 충분히 분리하신 이유가 이해갑니다. 만약 동일한 행동이지만, 나 자신의 프로필을 조회하는 것과 타인의 프로필을 조회하는 것을 분리하고 싶으시다면 지금처럼 동작해도 좋아보여요! 

통합/분리 외에 `findMyProfile` 쿼리가 `UserMapper` 파일에 존재하는게 조금 어색해보여요, 프로필 정보를 찾는건데 사용자 매퍼에서 쿼리를 수행하니까요.
또, 전자의 쿼리는 find 으로 시작하고, 두번째 쿼리는 get 으로 시작하고 있으니 find 으로 통일하는 등의 추가적인 메서드 명 개선이 필요한 것은 동일합니다!
